### ISSUE TITLE
Captura 

### ISSUE THREAD

**Issue by gilbertoalbino** [DevelopersRede/erede-php#11]
Ao realizar a Captura conforme exemplo:

```
// PV e TOKEN foram corretamente utilizados para criar uma transação com antifraude
// TID foi retornada na transação citada acima
$store = new \Rede\Store('PV', 'TOKEN');
// Transação que será capturada
$transaction =  (new \Rede\eRede($store))->capture((new \Rede\Transaction(20.99))->setTid('TID'));

if ($transaction->getReturnCode() == '00') {
    printf("Transação capturada com sucesso; tid=%s\n", $transaction->getTid());
}
```
Retorna o erro:

```
PHP Fatal error:  Uncaught Rede\Exception\RedeException: Unsuccessful. Please, contact Rede. in /var/www/html/vendor/developersrede/erede-php/src/Rede/Service/AbstractTransactionsService.php:86
Stack trace:
#0 /var/www/html/vendor/developersrede/erede-php/src/Rede/Service/AbstractService.php(141): Rede\Service\AbstractTransactionsService->parseResponse('{"returnCode":"...', 500)
#1 /var/www/html/vendor/developersrede/erede-php/src/Rede/Service/CaptureTransactionService.php(15): Rede\Service\AbstractService->sendRequest('{"amount":2099}', 'PUT')
#2 /var/www/html/vendor/developersrede/erede-php/src/Rede/eRede.php(81): Rede\Service\CaptureTransactionService->execute()
#3 /var/www/html/rede-capturar-transacao.php(8): Rede\eRede->capture(Object(Rede\Transaction))
#4 {main}
  thrown in /var/www/html/vendor/developersrede/erede-php/src/Rede/Service/AbstractTransactionsService.php on line 86
```
Debugando o response do CURL, resultou nisso:

 `"{"returnCode":"171","returnMessage":"Operation not allowed for this transaction."}"`

Alguma ideia do que possa estar ocorrendo?

**Comment by netojoaobatista** [comment]
O código de erro diz que essa operação não é permitida para essa transação. Isso pode acontecer por diversos motivos; um deles é a transação já ter sido capturada anteriormente, outro é uma transação de débito. Você tem que ter certeza de que a transação original era crédito e não foi capturada ainda.

**Comment by gilbertoalbino** [comment]
Procede, chefe!
A transação por padrão havia sido capturada!
